"""Add batch mode for unique constraints and size changes

Revision ID: 1419a283d960
Revises: a825afa564d4
Create Date: 2025-10-31 03:10:29.119585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1419a283d960'
down_revision = 'a825afa564d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_todo_content'), ['content'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_content'))
        batch_op.alter_column('content',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
