"""add deadline column to todo model.

Revision ID: 1e19ebd02140
Revises: ffaeda9f2780
Create Date: 2024-10-22 10:54:28.401388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e19ebd02140'
down_revision = 'ffaeda9f2780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'deadline')
    # ### end Alembic commands ###
