"""Add tag table

Revision ID: 904648732d66
Revises: 1e19ebd02140
Create Date: 2025-10-22 06:57:45.660605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904648732d66'
down_revision = '1e19ebd02140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
